// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Tpde-uARqg3SEbJwZcs4Fwbr4kVgLrk',
    appId: '1:1027518034716:web:55448b38366c815dac40d9',
    messagingSenderId: '1027518034716',
    projectId: 'finalproject-24728',
    authDomain: 'finalproject-24728.firebaseapp.com',
    storageBucket: 'finalproject-24728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ6RQcMILNKuNBCro7pRonvz2pRMGmgyQ',
    appId: '1:1027518034716:android:b5b4d5d9a77f1240ac40d9',
    messagingSenderId: '1027518034716',
    projectId: 'finalproject-24728',
    storageBucket: 'finalproject-24728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTT8PZJx03aZraAy7MoRXERuEx33v075E',
    appId: '1:1027518034716:ios:a008b68fdb1521bbac40d9',
    messagingSenderId: '1027518034716',
    projectId: 'finalproject-24728',
    storageBucket: 'finalproject-24728.appspot.com',
    iosClientId: '1027518034716-rvs1ev2j49q8d00lbc62re44pu2rpa6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
