// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6T0TPlsggvV5gIhXB8KtSeEbJkZhGhdo',
    appId: '1:76107524668:web:fbf82f1ccbc9dd67067139',
    messagingSenderId: '76107524668',
    projectId: 'e-farms',
    authDomain: 'e-farms.firebaseapp.com',
    storageBucket: 'e-farms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6ZRhzmStkSWiWOooRu9q6WcPMywWpzY',
    appId: '1:76107524668:android:a953e4c53f4f5b9f067139',
    messagingSenderId: '76107524668',
    projectId: 'e-farms',
    storageBucket: 'e-farms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC12kHdpAO3gXFnTg6tND7nLXI40kFweRs',
    appId: '1:76107524668:ios:bbaaa607491969fb067139',
    messagingSenderId: '76107524668',
    projectId: 'e-farms',
    storageBucket: 'e-farms.appspot.com',
    iosClientId: '76107524668-a1r1v1cq190mnhtq9735t71qvk01uec6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
